name: miaomiao
on:
  issues:
    types: [opened]
jobs:
  comment:
    if:
    runs-on: ubuntu-latest
    steps:
      - name: miaomiao
        uses: Marta83/funny-comment-action@v2.1
        id: FunnyComment
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }
            comment_type: 'git'
